### PR TITLE
Bug fixes to wrapper for VK_EXT_debug_utils

### PR DESCRIPTION
**Pull request by bzm3r**
This change is [Reviewable](https://reviewable.io/reviews/maikklein/ash/98)

### CODE REVIEW

**Comment by bzm3r** [comment]
You may have to squash my commits upon merging, because I was messy with them. 

https://help.github.com/articles/about-pull-request-merges/

**Comment by MaikKlein** [comment]
Can you remove the changes from`vk.rs`. It is generated and should not be authored. Do you also require `Eq`?.

Why do you want me to squash the commits?

**Comment by bzm3r** [comment]
@MaikKlein removed changes from vk.rs!

**Comment by MaikKlein** [comment]
You can use `git rebase -i` with squash or fixup.

**Comment by MaikKlein** [comment]
I integrated it myself, I hope you don't mind a10935eaf701845abac26dc433b43aadf29e2565

**Pull request closed without merging**
