### PR TITLE
Cover all features with clippy

### PR DESCRIPTION
**Pull request by Ralith**
Experimentally verified that this works as intended.

### CODE REVIEW

**Comment by MarijnS95** [comment]
Should we also do a run next to it with `--no-default-features`, and, if feasible, _also_ keep the default features? That sounds like the three most common configurations for the time being.

**Comment by Ralith** [comment]
Given that our features are independent, I don't think there's benefit to running clippy under any other configurations; we just want to be sure it sees all the code, and `--all-features` is sufficient for that. We might want to have `--no-default-features` coverage for other CI stages, but that can be pursued independently.

**Comment by MarijnS95** [comment]
Features are (supposed to be) additive, so it is indeed true that all code should be seen with `--all-features`. However, since that's not the default I'd also like the other extreme of no features at all to be tested, especially given "widespread" guards for the `"debug"` feature. That way we'll catch an accidental unconstrained `derive(Debug)` being added, for example.

Of course that won't find `linked` code accidentally referencing `loaded` code or vice-versa, but the chances for that seem way slimmer. I'd be fine to just have the `--no-default-features` stage under `clippy` too.
The `check` step is a bit useless as `clippy` performs that as a base pass too (or 99% of it).

**Comment by Ralith** [comment]
Added a clippy no-features case.

**Comment by MarijnS95** [comment]
Would have been fine for me to keep it under the same `steps` - should save another VM from being spun unnecessarily? I'd say it could reuse built dependencies but we don't have much of those.

**Comment by Ralith** [comment]
Folded them together.

**Review by MarijnS95 — APPROVED** [review]

**Pull request merged**
