### PR TITLE
Add create_compute_pipelines to device

### PR DESCRIPTION
**Pull request by msiglreith**

### CODE REVIEW

**Comment by MaikKlein** [comment]
Looks good, thanks!.

**Comment by msiglreith** [comment]
That was quick! Would you mind pushing a new version in the next days on crates.io?

**Comment by MaikKlein** [comment]
Yes I'll do it later today when I am on my dev machine again. I could also give you repository rights if that would make it easier for you.

**Comment by msiglreith** [comment]
Thanks! There is no need for access rights imo, most of the groundwork for the low level vulkan backend is done. Therefore I probably don't need a new version in the near future.

**Comment by MaikKlein** [comment]
@msiglreith done

**Comment by msiglreith** [comment]
Great! Just noticed that `0.15.6` was already published a week ago. Should this rather be `0.15.7`?

**Comment by MaikKlein** [comment]
You are right it didn't even publish. `cargo-release` is a bit buggy. I just manually published it now.

**Comment by msiglreith** [comment]
Thanks, it works 🎉

**Pull request closed without merging**
