### PR TITLE
Add `VK_KHR_timeline_semaphore` extension support

### PR DESCRIPTION
**Pull request by zedrian**
Introduced `ash::extensions::khr::TimelineSemaphore` structure written by analogy with `khr::Swapchain` (except the fact that it does not hold any special functions besides those ones that are needed for extension loading).

Enabling timeline semaphore support in the application now:
```rust
let device_extension_names = [
    ash::extensions::khr::TimelineSemaphore::name().as_ptr(),
    // other device extensions
];

let mut timeline_semaphore_features = vk::PhysicalDeviceTimelineSemaphoreFeatures::builder()
    .timeline_semaphore(true);

let device_create_info = vk::DeviceCreateInfo::builder()
    .enabled_extension_names(&device_extension_names)
    .push_next(&mut timeline_semaphore_features)
    // other settings
    .build();
let device = unsafe { instance.create_device(physical_device, &device_create_info, None)? };
```

### CODE REVIEW

**Comment by zedrian** [comment]
@farnoy I guess this PR may be interesting for you because you already requested this extension in #178  ☺

**Comment by zedrian** [comment]
@farnoy I tested on my side, functions related to timeline semaphores defined in `DeviceFnV1_2` become available just using `ash::device::Device`, e.g.
```rust
unsafe { device.wait_semaphores(device.handle(), &semaphore_wait_info, std::u64::MAX).unwrap(); }
```

so you don't have to grab function pointers by yourself anymore.

**Comment by farnoy** [comment]
Have you tested on a 1.0/1.1 application with this? I don't think that would work since the functions have a `KHR` suffix there. So using a `DeviceFnV1_2.get_semaphore_counter_value` would not work because it would try to load a `vkGetSemaphoreCounterValue`, whereas this extension should load `vkGetSemaphoreCounterValueKHR`.

**Comment by zedrian** [comment]
@farnoy I tried this on API 1.1, and it doesn't work. As I understand, that happens because of `VK_KHR_timeline_semaphore` appeared in Vulkan 1.2. 
Is this a problem?

**Comment by zedrian** [comment]
@farnoy I misread your comment at first, sorry. Yes, it will not work because of the `KHR` suffix in older versions of Vulkan.

**Comment by Ralith** [comment]
The point is, the extension should provide access to the `KHR`-suffixed versions, and therefore be usable on 1.1 impls.

**Comment by zedrian** [comment]
So expected implementation is that Vulkan 1.2 users call functions like
```rust
device.wait_semaphores(device.handle(), &semaphore_wait_info, timeout)?;
```
and Vulkan 1.1 users call functions like
```rust
timeline_semaphore_loader.wait_semaphores(&semaphore_wait_info, timeout)?;
```
right?

**Comment by farnoy** [comment]
I would summarize it as:

1.2 users don't use this and call `device.wait_semaphores(device.handle(), &semaphore_wait_info, timeout)?;`

1.0/1.1 users need to enable the device extension and call `timeline_semaphore_loader.wait_semaphores_khr(device.handle(), &semaphore_wait_info, timeout)?;`

I think the suffix is usually preserved in ash, and the interface should be the same (because it is the same in the spec between the extension and 1.2 core)

**Comment by zedrian** [comment]
BTW, `VK_KHR_timeline_semaphore` extension additionally requires `VK_KHR_get_physical_device_properties2`. But as I can see from my tests, it's enough to just add that extension name to the list of enabled extensions.

**Comment by zedrian** [comment]
I added the `*_khr` functions to the `TimelineSemaphore` as discussed, so the following code is available now for Vulkan 1.0/1.1 users:
```rust
timeline_semaphore_loader.get_semaphore_counter_value_khr(device.handle(), semaphore)?;

timeline_semaphore_loader.wait_semaphores_khr(device.handle(), &semaphore_wait_info, timeout)?;
timeline_semaphore_loader.signal_semaphore_khr(device.handle(), &semaphore_signal_info, timeout)?;
```

**Comment by MaikKlein** [comment]
Hey thanks for the PR. Sorry for not responding sooner. I made a PR to include function aliases in extensions https://github.com/MaikKlein/ash/pull/279


```Rust
pub struct KhrTimelineSemaphoreFn {
    pub get_semaphore_counter_value:
        extern "system" fn(device: Device, semaphore: Semaphore, p_value: *mut u64) -> Result,
    pub wait_semaphores: extern "system" fn(
        device: Device,
        p_wait_info: *const SemaphoreWaitInfo,
        timeout: u64,
    ) -> Result,
    pub signal_semaphore:
        extern "system" fn(device: Device, p_signal_info: *const SemaphoreSignalInfo) -> Result,
}

```

No need to fetch those function pointers yourself and we should update this PR when this is merged in.

**Comment by zedrian** [comment]
That would be great! Waiting for #279.

**Pull request merged**
