### PR TITLE
Fixes triangle example

### PR DESCRIPTION
**Pull request by 0x7CFE**
Pretty trivial fix. Just changed the types to make it compile.

### CODE REVIEW

**Comment by MaikKlein** [comment]
This should have been a `c_char`. On which system do you get a build error?

**Comment by 0x7CFE** [comment]
> This should have been a `c_char`. On which system do you get a build error?

Raspberry Pi 4 with a pre-alpha Vulkan drivers from here: https://blogs.igalia.com/apinheiro/2020/06/v3dv-quick-guide-to-build-and-run-some-demos/ :)

**Comment by MaikKlein** [comment]
> Raspberry Pi 4 with a pre-alpha Vulkan drivers from here: https://blogs.igalia.com/apinheiro/2020/06/v3dv-quick-guide-to-build-and-run-some-demos/ :)

Nice, do the examples work for you?

Also can you replace the pointer types with https://doc.rust-lang.org/std/os/raw/type.c_char.html instead of u8?

**Comment by 0x7CFE** [comment]
> Nice, do the examples work for you?

Yes, but only after some hacks. Notably: 

```diff
diff --git a/examples/src/lib.rs b/examples/src/lib.rs
index 1ffad3a..baaa475 100644
--- a/examples/src/lib.rs
+++ b/examples/src/lib.rs
@@ -361,7 +361,7 @@ impl ExampleBase {
 
             let create_info = vk::InstanceCreateInfo::builder()
                 .application_info(&appinfo)
-                .enabled_layer_names(&layers_names_raw)
+                //.enabled_layer_names(&layers_names_raw)
                 .enabled_extension_names(&extension_names_raw);
 
             let instance: Instance = entry
@@ -430,7 +430,8 @@ impl ExampleBase {
             let device_create_info = vk::DeviceCreateInfo::builder()
                 .queue_create_infos(&queue_info)
                 .enabled_extension_names(&device_extension_names_raw)
-                .enabled_features(&features);
+//                .enabled_features(&features)
+;
 
             let device: Device = instance
                 .create_device(pdevice, &device_create_info, None)
```

**Pull request closed without merging**
