### PR TITLE
C middleware compatibility enhancements

### PR DESCRIPTION
**Pull request by msiglreith**
Fixes https://github.com/MaikKlein/ash/issues/125 https://github.com/MaikKlein/ash/issues/126 

* Expose the define macros to allow generate custom vulkan handles
* Generate the raw PFN_ function types

I haven't run the generator as it generates one long, unformatted line of code for me, is this expected?

---
This change is [Reviewable](https://reviewable.io/reviews/maikklein/ash/150)

### CODE REVIEW

**Comment by MaikKlein** [comment]
Yes because rustfmt is not on stable as a library, I should document that. Sadly you have to format it manually with `rustup run stable rustfmt vk.rs`.

I think we will transition soon to a build script.

**Comment by msiglreith** [comment]
got it, thanks!
Added the formatted file in a separate commit

**Comment by MaikKlein** [comment]
@msiglreith Are you on the most up to date stable? The formatting looks a bit off, especially for macros.

**Comment by MaikKlein** [comment]
I merged it myself. Hm seems like Github doesn't detect that it has been merged. I'll release a new version soon!

**Comment by msiglreith** [comment]
oh that's the stable version of rustfmt. I'm mostly using the nightly preview so my stable fmt is quite dated (0.3.6-nightly ( )) 😅

**Comment by msiglreith** [comment]
ah, just was rebasing and squashing everything, heh
thanks for the quick review

**Comment by MaikKlein** [comment]
@msiglreith Yeah me too, but we needed to converge to a single rustfmt version otherwise we would always get a lot of different diffs.

I am just not sure why Github doesn't detect the merge.

**Pull request closed without merging**
