### PR TITLE
Omit wrapper functions on Fp structs

### PR DESCRIPTION
**Pull request by Ralith**
These wrappers contributed thousands of lines of code but offered insignificant ergonomic benefit as the same functions are also wrapped at a higher level and, if necessary, wrapper functions can be called directly. This will also make the doc search much less confusing.

No obvious impact to compile time on my machine, but dropping several thousand lines of code can't hurt.

### CODE REVIEW

**Comment by MarijnS95** [comment]
I've been longing for this change for quite some time, glad to see it finally happen!

Disappointing it doesn't contribute anything meaningful to compile times, though :/

**Comment by MarijnS95** [comment]
Don't forget to add an entry to the changelog, then I think we have enough material (in terms of open PRs) for the next breaking `ash` release :)

**Comment by Ralith** [comment]
Changelog updated. We really do just need to work out how to profile the compiler rather than relying on guesswork.

**Review by MarijnS95 — APPROVED** [review]
Haven't checked all of the ~7k line changes in detail, most of it looks good though.

**Pull request merged**
