### PR TITLE
[WIP] Khr Ray Tracing

### PR DESCRIPTION
**Pull request by Jasper-Bekkers**
To do this properly it needs a fix in `vk-parse` to parse one newly added attribute. Right now I just modified `vk.xml` locally to not have this attribute.

On top of that, this WIP break the nvidia extension so it probably shouldn't get merged in as-is.

### CODE REVIEW

**Comment by Friz64** [comment]
> To do this properly it needs a fix in `vk-parse` to parse one newly added attribute.

Should be fixed with this PR
https://github.com/krolli/vk-parse/pull/13

**Comment by cheako** [comment]
So "High level ray tracing support" probably shouldn't contain elements from what looks like a cargo-fmt?

**Comment by Jasper-Bekkers** [comment]
@Friz64 This seems to work well enough for my purposes, thanks for the heads up!

**Comment by cheako** [comment]
run ```git rebase -X theirs -i c32f0dd```
Erase the default plan and replace it with:
```
pick 62fe044 Generate vulkan ray-tracing bindings
x cargo-fmt && cargo-fmt && git add . && git commit --am -m"Generate vulkan ray-tracing bindings"
pick 6d1cc9f Add ray-tracing khr
x cargo-fmt && cargo-fmt && git add . && git commit --am -m"Add ray-tracing khr"
pick fb92760 High level ray tracing support
x cargo-fmt && cargo-fmt && git add . && git commit --am -m"High level ray tracing support"
pick da4f4fd Use new vk-parse do I don't have to have modifications in the Vulkan-Headers submodule anymore
x cargo-fmt && cargo-fmt && git add . && git commit --am -m"Use new vk-parse do I don't have to have modifications in the Vulkan-Headers submodule anymore"
```

**Comment by MaikKlein** [comment]
No need to format every commit, I'll squash them anyway.

**Comment by Friz64** [comment]
The `vk-parse` PR got merged, you can now use version 0.4 from crates.io.

**Comment by Jasper-Bekkers** [comment]
Nice!

@MaikKlein the reason that the Nvidia extension is broken seems to be missing handing of aliasses for functions.

**Comment by Jasper-Bekkers** [comment]
The last few commit made my current app that's using the NV extension work again. Probably not fully backwards compatible with all of the NV extension but good enough for my use-cases.

**Pull request merged**
