### PR TITLE
Make more structs derive PartialEq/Eq/Hash

### PR DESCRIPTION
**Pull request by swooster**
Adds equality-related traits to VkClearRect, VkOffset2D, VkOffset3D,
VkRect2D and VkSurfaceFormatKHR. Fixes a typo preventing said traits
from being applied to VkExtent2D.

### CODE REVIEW

**Comment by swooster** [comment]
NOTE: I haven't regenerated `vk.rs` because when I try to do that it comes out without newlines. (Maybe because I'm on Windows?) If somebody else is able to get that working, I'd be grateful.

**Comment by Ralith** [comment]
> I haven't regenerated vk.rs because when I try to do that it comes out without newlines.

This is the expected behavior; the workflow is to run `cargo fmt` after regenerating.

**Comment by aloucks** [comment]
I use `core.autocrlf=input` even on Windows and I think rustfmt will fallback to use native line endings if it can't detect any in the file (and I think the generated vk.rs is all on one line). 

Not sure if this will help your specific case, but I leave an uncommitted `rustfmt.toml` in my ash directory:

```toml
newline_style = "Unix"
```

**Comment by swooster** [comment]
Ok, thanks for the explanation. I've pushed a version of the commit with changes to `vk.rs` included.

**Pull request merged**
