### PR TITLE
Missing bits

### PR DESCRIPTION
**Pull request by filnet**
Add SamplerCreateFlags values.
Add missing PhysicalDeviceFeatures2Builder::push_next() function.

### CODE REVIEW

**Comment by Friz64** [comment]
You are changing generated code.
These changes should rather be produced by a `vk.xml` update.

**Comment by MaikKlein** [comment]
Those bitflags are already generated see https://docs.rs/ash/0.31.0/ash/vk/struct.SamplerCreateFlags.html#associatedconstant.SUBSAMPLED_EXT

But `all` is sadly incorrect right now. I opened an issue for it  https://github.com/MaikKlein/ash/issues/303

**Comment by filnet** [comment]
Oopsie... Worst part is that I knew that most of ash is generated.

Anyways, it helped find an issue with flags and extensions.

What about the missing push_next in PhysicalDeviceFeatures2Builder ?

**Comment by filnet** [comment]
Missing push_next() issue: https://github.com/MaikKlein/ash/issues/229

**Pull request closed without merging**
